# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20170301_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='Foreground_reddening',
            field=models.FloatField(blank=True, null=True, verbose_name='Foreground Reddening'),
        ),
        migrations.AddField(
            model_name='observation',
            name='Int_V_mag',
            field=models.FloatField(blank=True, null=True, verbose_name='Integrated V magnitude'),
        ),
        migrations.AddField(
            model_name='observation',
            name='dfgc',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance from the Galactic Centre [kpc]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dec',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC [degree]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dfs',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance from the Sun [kpc]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ra',
            field=models.FloatField(blank=True, null=True, verbose_name='RA [degree]'),
        ),
    ]
