# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20170815_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='Foreground_reddening',
        ),
        migrations.AddField(
            model_name='observation',
            name='FG_red',
            field=models.FloatField(blank=True, null=True, verbose_name='E(B-V)'),
        ),
        migrations.AddField(
            model_name='observation',
            name='V_horiz',
            field=models.FloatField(blank=True, null=True, verbose_name='V_HB'),
        ),
        migrations.AddField(
            model_name='observation',
            name='app_dist',
            field=models.FloatField(blank=True, null=True, verbose_name='(m-M)V'),
        ),
        migrations.AddField(
            model_name='observation',
            name='gc_x',
            field=models.FloatField(blank=True, null=True, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='observation',
            name='gc_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y'),
        ),
        migrations.AddField(
            model_name='observation',
            name='gc_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Z'),
        ),
        migrations.AddField(
            model_name='observation',
            name='lg_th',
            field=models.FloatField(blank=True, null=True, verbose_name='Median relaxation time'),
        ),
        migrations.AddField(
            model_name='observation',
            name='lg_tx',
            field=models.FloatField(blank=True, null=True, verbose_name='Core relaxation time'),
        ),
        migrations.AddField(
            model_name='observation',
            name='spec_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='spt'),
        ),
        migrations.AddField(
            model_name='observation',
            name='v_LSR',
            field=models.FloatField(blank=True, null=True, verbose_name='v_LSR'),
        ),
        migrations.AddField(
            model_name='observation',
            name='v_err',
            field=models.FloatField(blank=True, null=True, verbose_name='uncertainty'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='Int_V_mag',
            field=models.FloatField(blank=True, null=True, verbose_name='V_t'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dec',
            field=models.FloatField(blank=True, null=True, verbose_name='DEC'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dfgc',
            field=models.FloatField(blank=True, null=True, verbose_name='D-GC'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dfs',
            field=models.FloatField(blank=True, null=True, verbose_name='D-sun'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ellipticity',
            field=models.FloatField(blank=True, null=True, verbose_name='Ellip'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='gallat',
            field=models.FloatField(blank=True, null=True, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='gallon',
            field=models.FloatField(blank=True, null=True, verbose_name='Long'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='m_v_t',
            field=models.FloatField(blank=True, null=True, verbose_name='Luminosity'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ra',
            field=models.FloatField(blank=True, null=True, verbose_name='RA'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sig_err',
            field=models.FloatField(blank=True, null=True, verbose_name='uncertainty'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sig_v',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocity dispersion'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='v_r',
            field=models.FloatField(blank=True, null=True, verbose_name='Heliocentric radial velocity'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='w_mean_met',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
