# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_submitform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmitForm',
            new_name='Submitted',
        ),
    ]
