# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20170817_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitted',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
