# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20170815_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='metallicityandphotometry',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='metallicityandphotometry',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='velocitiesandstructuralparameter',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='velocitiesandstructuralparameter',
            name='ref',
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.DeleteModel(
            name='MetallicityAndPhotometry',
        ),
        migrations.DeleteModel(
            name='VelocitiesAndStructuralParameter',
        ),
    ]
