# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20170815_1519'),
        ('catalogue', '0006_submitted_created_by'),
    ]

    operations = [
    ]
