# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_merge_20170920_1711'),
        ('catalogue', '0007_submitted_status'),
    ]

    operations = [
    ]
